<a href="https://colab.research.google.com/github/hdpark1208/StudyCode/blob/main/NLP/NLP_SplittingData%26PreprocessingTools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* zip() : 동일한 개수를 가지는 시퀀스 자료형에서 각 순서에 등장하는 원소들끼리 묶어주는 함수

In [ ]:
X,y = zip(['a',1],['b',2],['c',3])
print(X,type(X))
print(y,type(y))

('a', 'b', 'c') <class 'tuple'>
(1, 2, 3) <class 'tuple'>


In [ ]:
sequences=[['a', 1], ['b', 2], ['c', 3]] # 리스트의 리스트 또는 행렬 또는 뒤에서 배울 개념인 2D 텐서
X,y = zip(*sequences) # *를 추가
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


## 판다스를 이용

In [ ]:
import pandas as pd

In [ ]:
values = [['당신에게 드리는 마지막 혜택!',1],
         ['내일 뵐 수 있을지 확인 부탁드...',0],
         ['도연씨, 잘 지내시죠? 오래만입...',0],
         ['(광고)AI로 주가를 예측할 수 있다!',1]]
columns = ['메일 본문','스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0       당신에게 드리는 마지막 혜택!         1
1   내일 뵐 수 있을지 확인 부탁드...         0
2   도연씨, 잘 지내시죠? 오래만입...         0
3  (광고)AI로 주가를 예측할 수 있다!         1

In [ ]:
X = df['메일 본문']
y = df['스팸 메일 유무']

In [ ]:
X

0         당신에게 드리는 마지막 혜택!
1     내일 뵐 수 있을지 확인 부탁드...
2     도연씨, 잘 지내시죠? 오래만입...
3    (광고)AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object

In [ ]:
y

0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64

## 넘파이를 이용

In [ ]:
import numpy as np
ar = np.arange(0,16).reshape((4,4))
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
X = ar[:,:3]
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [ ]:
y = ar[:,3]
y

array([ 3,  7, 11, 15])

## 사이킷런을 이용

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
X_train

array([[ 8,  9, 10],
       [ 0,  1,  2],
       [ 4,  5,  6]])

In [ ]:
y_train

array([11,  3,  7])

# 한국어 전처리 패키지

## Pykospacing

In [ ]:
# !pip install git+https://github.com/haven-jeon/PyKoSpacing.git

  Cloning https://github.com/haven-jeon/PyKoSpacing.git to c:\users\user\appdata\local\temp\pip-req-build-5tinyah1


  ERROR: Error [WinError 2] 지정된 파일을 찾을 수 없습니다 while executing command git clone -q https://github.com/haven-jeon/PyKoSpacing.git 'C:\Users\User\AppData\Local\Temp\pip-req-build-5tinyah1'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?


In [ ]:
# 깃 설치 필요하다