<a href="https://colab.research.google.com/github/hdpark1208/StudyCode/blob/main/CryptoWorkoutWeek4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Substitution 암호

In [ ]:
C='LWNSOZBNWVWBAYBNVBSQWVWOHWDIZWRBBNPBPOOUWRPAWXAW\
PBWZWMYPOBNPBBNWJPAWWRZSLWZQJBNWIAXAWPBSALIBNXWA\
BPIRYRPOIWRPQOWAIENBVBNPBPUSREBNWVWPAWOIHWOIQWAB\
JPRZBNWFYAVYIBSHNPFFIRWVVBNPBBSVWXYAWBNWVWAIENBV\
ESDWARUWRBVPAWIRVBIBYBWZPUSREUWRZWAIDIREBNWIATYV\
BFSLWAVHASUBNWXSRVWRBSHBNWESDWARWZBNPBLNWRDWAPR\
JHSAUSHESDWARUWRBQWXSUWVZWVBAYXBIDWSHBNWVWWRZVIB\
IVBNWAIENBSHBNWFWSFOWBSPOBWASABSPQSOIVNIBPRZBSIR\
VBIBYBWRWLESDWARUWRBOPJIREIBVHSYRZPBISRSRVYXNFAI\
RXIFOWVPRZSAEPRIKIREIBVFSLWAVIRVYXNHSAUPVBSVWWUU\
SVBOICWOJBSWHHWXBBNWIAVPHWBJPRZNPFFIRWVV'

암호문에서 각 알파벳의 빈도를 구해봅시다. 딕셔너리 자료형은 `{}`로 양쪽을 가둬서 정의하고,  키(key)와 값(value)의 쌍으로 이루어집니다.
아래의 코드의 출처는 [Stackoverflow](https://stackoverflow.com/questions/40985203/counting-letter-frequency-in-a-string-python/40985309)와 [Python 공식문서](https://docs.python.org/ko/3/howto/sorting.html)입니다.

In [ ]:
def char_frequency(str1):
  dict = {}
  for n in str1:   # 암호문을 첫글자부터 하나씩 골라서 반복합니다. 
    keys = dict.keys()
    if n in keys: # 이미 저장된 글자이면 빈도(value)를 하나 증가시키고 
      dict[n] += 1
    else:  # 처음 나오는 글자이면 새로운 알파벳(key)와 value(빈도) 1로 딕셔너리에 추가합니다
      dict[n] = 1
  return dict

dict1 = char_frequency(C)
print(dict1)
# sorted()라는 명령어를 이용하여 빈도를 기준으로 정렬하도록 합니다.
print(sorted(dict1.items(), reverse=True, key=lambda item: item[1])) 

{'L': 7, 'W': 75, 'N': 30, 'S': 36, 'O': 16, 'Z': 15, 'B': 64, 'V': 35, 'A': 34, 'Y': 13, 'Q': 6, 'H': 14, 'D': 8, 'I': 36, 'R': 39, 'P': 32, 'U': 13, 'X': 11, 'M': 1, 'J': 7, 'E': 13, 'F': 11, 'T': 1, 'K': 1, 'C': 1}
[('W', 75), ('B', 64), ('R', 39), ('S', 36), ('I', 36), ('V', 35), ('A', 34), ('P', 32), ('N', 30), ('O', 16), ('Z', 15), ('H', 14), ('Y', 13), ('U', 13), ('E', 13), ('X', 11), ('F', 11), ('D', 8), ('L', 7), ('J', 7), ('Q', 6), ('M', 1), ('T', 1), ('K', 1), ('C', 1)]


보통의 영어 문장들에서 잘 나오는 알파벳들의 비율은 다음과 같습니다. $(e, .127), (t, .091), (a, .082), (o, .075), (i, .070), (n, .067), (s, .063), (h, .061), (r, .060)$

이로부터 'W'는 'e'에 대응한다는 것을 추측할 수 있습니다. (또는 'B'가 'e'에 대응할 가능성도 있습니다.)
하지만 나머지 알파벳들에 대해 더 이상 추측하기는 어렵습니다. 

지금부터는 bigram(알파벳 두글자)의 빈도를 이용합니다.
가장 많이 나온 알파벳들 'W, B, R, S, I, V, A, P, N'중에서 두글자로 나오는 빈도를 세봅시다.

In [ ]:
list1 = ['W', 'B', 'R', 'S', 'I', 'V', 'A', 'P', 'N']
count_matrix = [] # 전체 빈도를 기록할 행렬입니다
for i in range(len(list1)):
  count_row = [] # 해당 행(row)의 빈도를 기록할 행(list)입니다
  for j in range(len(list1)):
    count = 0 # 해당 bigram의 빈도를 기록할 변수입니다
    for k in range(len(C)-1): #bigram이므로 가장 마지막보다 하나 적은 위치까지만 보면 됩니다
      if list1[i]+list1[j]==C[k:k+2]:
        count += 1
    count_row.append(count)
  count_matrix.append(count_row)

print(count_matrix)  

[[3, 4, 12, 2, 4, 10, 14, 3, 1], [4, 4, 0, 11, 5, 5, 2, 4, 20], [4, 5, 0, 1, 1, 5, 0, 3, 0], [1, 0, 5, 0, 1, 3, 5, 2, 0], [1, 8, 10, 1, 0, 2, 3, 0, 0], [8, 10, 0, 0, 2, 2, 0, 3, 1], [7, 3, 4, 2, 5, 4, 0, 1, 0], [0, 8, 6, 0, 1, 1, 4, 0, 0], [14, 3, 0, 1, 1, 1, 0, 7, 0]]


## Hill Cipher

알파벳을 $n$개씩 Block 단위로 암호화하는 암호방식

성분이 $Z_{26}$의 원소들인 $n \times n$ 행렬 $M$을 암호화 키로 이용하고 그 역행렬 ( $Z_{26}$ 에서)을 이용해서 복호화

알고리즘: 평문을 알파벳 $n$개씩 나눠서 n차원 벡터($Z_{26}^n$)로 보고 암호화 키는 $n^2$ 길이의 알파벳을  $Z_{26}$의 원소들인 $n \times n$ 행렬 $M$로 변환하여 행렬곱셈을 행하고,
복호화는 그 역행렬을 곱함터($Z_{26}^n$)로 보고 암호화 키는 $n^2$ 길이의 알파벳을  $Z_{26}$의 원소들인 $n \times n$ 행렬 $M$로 변환하여 행렬곱셈을 행하고,
복호화는 그 역행렬을 곱함







먼저 평문과 키를 $Z_{26}$의 벡터와 행렬로 바꾸는 작업을 합시다.


In [ ]:
def plain_to_numbers(P):
  l = []
  for i in range(len(P)):
    l.append(ord(P[i])-ord('a'))
  return l

def numbers_to_cipher(l):
  C = ''
  for i in range(len(l)): 
    C = C + chr(l[i]+ord('A'))
  return C

In [ ]:
def key_to_matrix(K):
  n = int(len(K)**(1/2))
  if len(K)!=n*n:  # 키 길이가 n*n이 아닐 경우 처리
    print("Wrong Key!")
    return
  keyMatrix = [[0] * n for i in range(n)] 
  k = 0
  for i in range(n): # i: 행 지표(index)
    for j in range(n): # j: 열 지표(index)
      keyMatrix[i][j] = ord(K[k])-ord('A')
      k += 1
  return keyMatrix


In [ ]:
def HillCipher_Multiplication(l, M):
  n = len(M)
  C =[0]*n
  for j in range(n):
    for k in range(n):
      C[j] = (C[j] + l[k]*M[k][j]) % 26
  return C
    

In [ ]:
def HillCipher_Encrypt(P, K):
  n = int(len(K)**(1/2))
  while len(P)%n != 0:  # 평문의 길이가 n의 배수가 아닐때, 끝에 알파벳 a를 붙입니다
    P += 'a'
  l = plain_to_numbers(P)
#  print(l)
  keyMatrix = key_to_matrix(K)
#  print(keyMatrix)  #테스트 코드
  C = []
  for i in range(len(P)//n):
#    print(l[i*3:(i+1)*3])  # 테스트 코드
    C = C + (HillCipher_Multiplication(l[i*n:(i+1)*n], keyMatrix))
#  print(C) # 테스트 코드
  return numbers_to_cipher(C)

In [ ]:
HillCipher_Encrypt('hello', 'GYBNQKURP')
# 여기서 확인해봅시다, Hill Cipher 시작부분에서 n 값을 지정하고 차례대로 실행해야 합니다

'CDEOUV'

이제 복호화를 해봅시다.
환 $Z_{26}$에서 역행렬을 구하는 것은 복잡하므로 numpy 라이브러리를 이용합시다.

* 행렬 A의 행렬식(determinant): `numpy.linalg.det(A)`
* A의 역행렬: `numpy.linalg.inv(A)`
* 위 연산의 결과는 성분이 실수인 행렬이 되는데, `round()` 와 같은 명령으로 정수형 행렬로 변환. (주의: int(1.99999)는 1이됨)

In [ ]:
import numpy as np

In [ ]:
def HillCipher_Decrypt(C, K):
  n = int(len(K)**(1/2))
  if len(C)%n !=0: # 암호문의 길이는 n의 배수여야 합니다!
    print("암호문의 길이가 맞지 않습니다!")
    return
  l = plain_to_numbers(C.lower())
  keyMatrix = key_to_matrix(K)

  det = round(np.linalg.det(keyMatrix)) % 26 # 암호화 키 행렬의 행렬식을 정수형으로 바꿉니다
# print(det) # 테스트 코드
  if (det % 2 == 0) or (det % 13 == 0): 
    print("키의 역행렬을 구할 수 없습니다!")
    return
  det_inv = None
  for i in range(26): # 여기서는 Z_26에서 행렬식의 역수 det_inv를 구합니다
    if (det*i) % 26 == 1:
      det_inv = i
      break

#  print(det_inv)  # 테스트 코드

  invMatrix = np.linalg.det(keyMatrix)*np.linalg.inv(keyMatrix)
#  print(invMatrix) # 테스트 코드

  for i in range(n):
    for j in range(n):
      keyMatrix[i][j] = (round(invMatrix[i][j])*det_inv) % 26


#  print(keyMatrix)  # 테스트 코드
  P = []
  for i in range(len(C)//n):
    P = P + (HillCipher_Multiplication(l[i*n:(i+1)*n], keyMatrix))
#  print(P) # 테스트 코드
  return numbers_to_cipher(P).lower()

  

In [ ]:
HillCipher_Decrypt('CDEOUV', 'GYBNQKURP')  
# 여기서 확인해봅시다! Hill Cipher 시작부분에서 n 값을 지정하고 차례대로 실행해야 합니다

'helloa'

In [ ]:
HillCipher_Decrypt(HillCipher_Encrypt('hillcipherisfun', 'GYBNQKURP'), 'GYBNQKURP')

'hillcipherisfun'

## 실습문제

다음 Hill Cipher의 암호문이 암호화 키 `K = BCDEEDCBLCEGCJGE`로 암호화 되었다. 이를 복호화하여라.
`C=ZIRKZWOPJJOPTFAPUHFHADRQ`

In [ ]:
HillCipher_Decrypt('ZIRKZWOPJJOPTFAPUHFHADRQ', 'BCDEEDCBLCEGCJGE')  
# 여기서 확인해봅시다! Hill Cipher 시작부분에서 n 값을 지정하고 차례대로 실행해야 합니다

'jackandjillwentupthehill'

# LFSR(Lienar Feedback Shift Register) 수열
이번에는 LFSR(Linear Feedback Shift Register) 수열을 생성하고 해독하는 방법에 대해 알아봅시다

* 초기값들(Initial Values) : $[x_1, x_2, ..., x_m]$
* 계수들(Coefficients) : $[c_0, c_1, ..., c_{m-1}]$
* 알고리즘: $x_{n+m} \equiv c_0 x_n + c_1 x_{n+1} + \cdots + c_{m-1} x_{n+m-1} (mod 2)$

In [ ]:
InitialValues = [0, 1, 0, 0, 0]
Coefficients = [1, 0, 1, 0, 0]
MaximalNumbers = 100  # 추가로 계산하고 싶은 수열의 갯수
LFSR = InitialValues + [0]*MaximalNumbers # 일단 처음 m개에 추가로 0값을 갖는 자리를 확보
m = len(InitialValues)
for n in range(MaximalNumbers):
  LFSR[m+n] = sum(Coefficients[j]*LFSR[n+j] for j in range(m)) % 2

print(LFSR)


[0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1]


list 형의 LFSR 수열을 보기좋게 strings 자료형으로 반환하는 함수와 그런 strings 형의 LFSR 수열을 list 형을 반환하는 함수를 작성해봅시다.

In [ ]:
def LFSR_to_strings(LFSR):  
# 이 함수는 list형태로 구한 LFSR 수열을 보기좋게 strings형태로 바꿔주는 함수입니다
  s = ''
  for i in range(len(LFSR)):
    s = s + str(LFSR[i])
  return s

def strings_to_LFSR(s):
# 이 함수는 strings형태의 LFSR 수열을 list형태로 반환하는 함수입니다
  l = []
  for i in range(len(s)):
    l.append(int(s[i]))
  return l


In [ ]:
s = LFSR_to_strings(LFSR)
print(s)
print(strings_to_LFSR(s)) # 여기서 확인해봅시다

010000100101100111110001101110101000010010110011111000110111010100001001011001111100011011101010000100101
[0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1]


## LSFR 분석하기

강의에서 설명한 정리를 이용해서 행렬 $M_n$을 구성하고 $\det(M_n) (n=1, 2, ...)$을 계산하여 LFSR 수열을 생성하는 최소의 점화식의 길이 $N$을 구해봅시다.

In [ ]:
import numpy as np

In [ ]:
for n in range(1, len(LFSR)//2):
  M1 = []
  for i in range(n):
    M1.append(LFSR[i:i+n])
  M = np.array(M1, dtype=np.int16)  
  print("n = {:2d}: det(M_n) (mod 2) = {}".format(n, round(np.linalg.det(M)) % 2))

#  print(M) # 테스트 코드


n =  1: det(M_n) (mod 2) = 0
n =  2: det(M_n) (mod 2) = 1
n =  3: det(M_n) (mod 2) = 0
n =  4: det(M_n) (mod 2) = 0
n =  5: det(M_n) (mod 2) = 1
n =  6: det(M_n) (mod 2) = 0
n =  7: det(M_n) (mod 2) = 0
n =  8: det(M_n) (mod 2) = 0
n =  9: det(M_n) (mod 2) = 0
n = 10: det(M_n) (mod 2) = 0
n = 11: det(M_n) (mod 2) = 0
n = 12: det(M_n) (mod 2) = 0
n = 13: det(M_n) (mod 2) = 0
n = 14: det(M_n) (mod 2) = 0
n = 15: det(M_n) (mod 2) = 0
n = 16: det(M_n) (mod 2) = 0
n = 17: det(M_n) (mod 2) = 0
n = 18: det(M_n) (mod 2) = 0
n = 19: det(M_n) (mod 2) = 0
n = 20: det(M_n) (mod 2) = 0
n = 21: det(M_n) (mod 2) = 0
n = 22: det(M_n) (mod 2) = 0
n = 23: det(M_n) (mod 2) = 0
n = 24: det(M_n) (mod 2) = 0
n = 25: det(M_n) (mod 2) = 0
n = 26: det(M_n) (mod 2) = 0
n = 27: det(M_n) (mod 2) = 0
n = 28: det(M_n) (mod 2) = 0
n = 29: det(M_n) (mod 2) = 0
n = 30: det(M_n) (mod 2) = 0
n = 31: det(M_n) (mod 2) = 1
n = 32: det(M_n) (mod 2) = 0
n = 33: det(M_n) (mod 2) = 0
n = 34: det(M_n) (mod 2) = 0
n = 35: det(M_

이제 알아낸 점화식의 길이 $N$을 이용해서 점화식(점화식의 계수들을) 알아내봅시다.

* 행렬 `A, B`의 곱:  `np.matmul(A, B)`
* 행렬 `A`의 전치행렬: `np.transpose(A)`
* 마지막으로  `[0]`를 이용해서 행렬안에 있는 array를 꺼내면 됩니다.

In [ ]:
N = 5
M1 = []
CoffMatrix = []
for i in range(N):
  M1.append(LFSR[i:i+N])
  CoffMatrix.append([LFSR[i+N]])

#print(CoffMatrix)
invMatrix = np.linalg.det(M1) * np.linalg.inv(M1)
# print(invMatrix) # 테스트 코드

M = []
for i in range(N):
  M.append([round(invMatrix[i][j]) % 2 for j in range(N)])

# print(M)

Coff = np.transpose(np.matmul(M, CoffMatrix))[0] 
for i in range(N):
  Coff[i] = Coff[i] % 2

print(Coff)

[1 0 1 0 0]


## 실습문제 2
다음 LFSR 수열로부터 점화식(계수들의 list)을 알아내어라.

`L100 = [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]`

`L101= [1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 
      1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 
      0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 
      0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 
      0, 0]`

In [ ]:
L100 = [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
L101 = [1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0]
LFSR = L101
for n in range(1, len(LFSR)//2):
  M1 = []
  for i in range(n):
    M1.append(LFSR[i:i+n])
  M = np.array(M1, dtype=np.float64)#np.int16
  print("n = {:2}: det(M_n) (mod 2) = {}".format(n, round(np.linalg.det(M)) % 2))

n =  1: det(M_n) (mod 2) = 1
n =  2: det(M_n) (mod 2) = 1
n =  3: det(M_n) (mod 2) = 1
n =  4: det(M_n) (mod 2) = 0
n =  5: det(M_n) (mod 2) = 1
n =  6: det(M_n) (mod 2) = 1
n =  7: det(M_n) (mod 2) = 0
n =  8: det(M_n) (mod 2) = 0
n =  9: det(M_n) (mod 2) = 0
n = 10: det(M_n) (mod 2) = 0
n = 11: det(M_n) (mod 2) = 0
n = 12: det(M_n) (mod 2) = 0
n = 13: det(M_n) (mod 2) = 0
n = 14: det(M_n) (mod 2) = 0
n = 15: det(M_n) (mod 2) = 0
n = 16: det(M_n) (mod 2) = 0
n = 17: det(M_n) (mod 2) = 0
n = 18: det(M_n) (mod 2) = 0
n = 19: det(M_n) (mod 2) = 0
n = 20: det(M_n) (mod 2) = 0
n = 21: det(M_n) (mod 2) = 0
n = 22: det(M_n) (mod 2) = 0
n = 23: det(M_n) (mod 2) = 0
n = 24: det(M_n) (mod 2) = 0
n = 25: det(M_n) (mod 2) = 0
n = 26: det(M_n) (mod 2) = 0
n = 27: det(M_n) (mod 2) = 0
n = 28: det(M_n) (mod 2) = 0
n = 29: det(M_n) (mod 2) = 0
n = 30: det(M_n) (mod 2) = 0
n = 31: det(M_n) (mod 2) = 0
n = 32: det(M_n) (mod 2) = 0
n = 33: det(M_n) (mod 2) = 0
n = 34: det(M_n) (mod 2) = 0
n = 35: det(M_

In [ ]:
N = 6
M1 = []
CoffMatrix = []
for i in range(N):
  M1.append(LFSR[i:i+N])
  CoffMatrix.append([LFSR[i+N]])

#print(CoffMatrix)
invMatrix = np.linalg.det(M1)*np.linalg.inv(M1)
# print(invMatrix) # 테스트 코드

M = []
for i in range(N):
  M.append([round(invMatrix[i][j]) % 2 for j in range(N)])

# print(M)

Coff = np.transpose(np.matmul(M, CoffMatrix))[0] 
for i in range(N):
  Coff[i] = Coff[i] % 2

print(Coff)

[1 1 0 1 1 0]


In [ ]:
LFSR = L100
for n in range(1, len(LFSR)//2):
  M1 = []
  for i in range(n):
    M1.append(LFSR[i:i+n])
  M = np.array(M1, dtype=np.float64)#np.int16
  print("n = {:2}: det(M_n) (mod 2) = {}".format(n, round(np.linalg.det(M)) % 2))

n =  1: det(M_n) (mod 2) = 1
n =  2: det(M_n) (mod 2) = 0
n =  3: det(M_n) (mod 2) = 1
n =  4: det(M_n) (mod 2) = 0
n =  5: det(M_n) (mod 2) = 0
n =  6: det(M_n) (mod 2) = 1
n =  7: det(M_n) (mod 2) = 0
n =  8: det(M_n) (mod 2) = 1
n =  9: det(M_n) (mod 2) = 0
n = 10: det(M_n) (mod 2) = 0
n = 11: det(M_n) (mod 2) = 0
n = 12: det(M_n) (mod 2) = 0
n = 13: det(M_n) (mod 2) = 0
n = 14: det(M_n) (mod 2) = 0
n = 15: det(M_n) (mod 2) = 0
n = 16: det(M_n) (mod 2) = 0
n = 17: det(M_n) (mod 2) = 0
n = 18: det(M_n) (mod 2) = 0
n = 19: det(M_n) (mod 2) = 0
n = 20: det(M_n) (mod 2) = 0
n = 21: det(M_n) (mod 2) = 0
n = 22: det(M_n) (mod 2) = 0
n = 23: det(M_n) (mod 2) = 0
n = 24: det(M_n) (mod 2) = 0
n = 25: det(M_n) (mod 2) = 0
n = 26: det(M_n) (mod 2) = 0
n = 27: det(M_n) (mod 2) = 0
n = 28: det(M_n) (mod 2) = 0
n = 29: det(M_n) (mod 2) = 0
n = 30: det(M_n) (mod 2) = 0
n = 31: det(M_n) (mod 2) = 0
n = 32: det(M_n) (mod 2) = 0
n = 33: det(M_n) (mod 2) = 0
n = 34: det(M_n) (mod 2) = 0
n = 35: det(M_

In [ ]:
N = 8
M1 = []
CoffMatrix = []
for i in range(N):
  M1.append(LFSR[i:i+N])
  CoffMatrix.append([LFSR[i+N]])

#print(CoffMatrix)
invMatrix = np.linalg.det(M1)*np.linalg.inv(M1)
# print(invMatrix) # 테스트 코드

M = []
for i in range(N):
  M.append([round(invMatrix[i][j]) % 2 for j in range(N)])

# print(M)

Coff = np.transpose(np.matmul(M, CoffMatrix))[0] 
for i in range(N):
  Coff[i] = Coff[i] % 2

print(Coff)

[1 1 0 0 1 0 0 0]
